// Automatically generated by astro-icon
// 27bdb28a4a570810c74e315bf50bbd26bf2fd2e92249f810cddfeb364e759b0c

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ic:round-arrow-left"
		| "ic:round-arrow-right"
		| "octicon:triangle-up-24";
}