// Automatically generated by astro-icon
// fe5fb24306a40aab49da8a5c5cf457328e4a5cf2284728d8b2df0f807cbbea97

declare module 'virtual:astro-icon' {
    export type Icon =
        | 'ic:round-arrow-left'
        | 'ic:round-arrow-right'
        | 'octicon:triangle-up-24'
        | 'favicon';
}
